### ISSUE TITLE
how to get the rendering?

### ISSUE THREAD

**Issue by kraftpunk97** [klowrey/MuJoCo.jl#10]
Hi. If one was to render the output to a screen what would they have to do?

**Comment by klowrey** [comment]
https://github.com/klowrey/MujocoSim.jl

I just dumped some code into the repo above. It's based off the simulate.cpp code in the mujoco package.

In it's existing form it loads a mujoco model and simulates passive dynamics. It can be modified for whatever your use case may be.

**Comment by kraftpunk97** [comment]
I see. Thanks
