### ISSUE TITLE
Simple Visualize Window

### ISSUE THREAD

**Issue by jpp46** [klowrey/MuJoCo.jl#12]
There is no example on this but is there any easy way to visualize a simulation

**Comment by klowrey** [comment]
This just wraps the mujoco c library; I've made a separate repo: https://github.com/klowrey/MujocoSim.jl for  visualizing models.

It's set up to allow you to customize what you're visualizing and is built up from a previous version of the mujoco simulate.cpp example code.

I'll add a note to the README for others.
