### ISSUE TITLE
Demo in README not working

### ISSUE THREAD

**Issue by jpp46** [klowrey/MuJoCo.jl#9]
I am on a Mac and MuJoCo by itself and every other part of the demo code in the readme works except these lines of code and their following errors:

**mj.set(m, :opt, :timestep, -0.002)**

ERROR: MethodError: no method matching update_ptr(::Base.RefValue{mjModel}, ::UInt64, ::Float64)
Closest candidates are:
  update_ptr(::Ptr, ::Integer, ::Float64) at /Users/powers/.julia/packages/MuJoCo/GRTFJ/src/mjextra.jl:152
  update_ptr(::Ptr, ::Integer, ::Integer) at /Users/powers/.julia/packages/MuJoCo/GRTFJ/src/mjextra.jl:149
  update_ptr(::Ptr, ::Integer, ::StaticArrays.SArray{Tuple{S},T,1,S} where T where S) at /Users/powers/.julia/packages/MuJoCo/GRTFJ/src/mjextra.jl:155
Stacktrace:
 [1] set(::jlModel, ::Symbol, ::Symbol, ::Float64) at /Users/powers/.julia/packages/MuJoCo/GRTFJ/src/mjextra.jl:204
 [2] top-level scope at none:0

**m.m[].opt.timestep = 0.002**

ERROR: setfield! immutable struct of type mjOption cannot be changed
Stacktrace:
 [1] setproperty!(::mjOption, ::Symbol, ::Float64) at ./sysimg.jl:19
 [2] top-level scope at none:0

**d.qpos[:] = rand(nq)**

ERROR: UndefVarError: nq not defined
Stacktrace:
 [1] top-level scope at none:0

**Comment by klowrey** [comment]
Thanks Joshua. I've removed the offending lines from the readme for now; there is a re-write in the works to make things both faster to index into structs and more Julian.

Currently things like performing rollouts for RL or trajectory optimization are as fast as C code, so if there's other functionality needed let me know.
